### ISSUE TITLE
Compass?

### ISSUE THREAD

**Issue by themaxx** [vigetlabs/sass-json-vars#9]
Is it possible to use sass-json-vars with Compass? I can't get it to work. I'd appreciate any insights. Stack trace follows. (This works if I use `sass sass/screen.scss -r sass-json-vars` instead.)

```
$ compass w -r sass-json-vars --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
TypeError on line ["39"] of /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/importers/filesystem.rb: no implicit conversion of nil into String
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/importers/filesystem.rb:39:in `key'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/importer.rb:19:in `key'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/importer.rb:56:in `import_tracker_key'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/importer.rb:65:in `imported?'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/importer.rb:43:in `maybe_replace_with_dummy_engine'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/importer.rb:12:in `find'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/import_node.rb:54:in `block in import'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/import_node.rb:53:in `each'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/import_node.rb:53:in `import'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/import_node.rb:28:in `imported_file'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/import_node.rb:37:in `css_import?'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:283:in `visit_import'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:36:in `visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:152:in `block in visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/stack.rb:79:in `block in with_base'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/stack.rb:121:in `with_frame'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/stack.rb:79:in `with_base'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:152:in `visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:52:in `map'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:52:in `visit_children'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:161:in `block in visit_children'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:173:in `with_environment'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:160:in `visit_children'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:36:in `block in visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:180:in `visit_root'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/base.rb:36:in `visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:151:in `visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/visitors/perform.rb:8:in `visit'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/root_node.rb:36:in `css_tree'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/tree/root_node.rb:20:in `render'
  /Users/ray/.gem/ruby/2.0.0/gems/sass-3.3.11/lib/sass/engine.rb:274:in `render'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/engine.rb:17:in `block in render'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/engine.rb:29:in `with_import_scope'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-import-once-1.0.4/lib/compass/import-once/engine.rb:16:in `render'
  /Users/ray/.gem/ruby/2.0.0/gems/compass-1.0.0.alpha.21/lib/compass/compiler.rb:171:in `block (2 levels) in compile'
[...]
```

**Comment by mooror** [comment]
Hey nhunzaker, I just wanted to let you know that I was able to use the setup you show in the link to make sass-json-vars work with compass. Cheers!

**Comment by nhunzaker** [comment]
Sweet! Thank you!
